version: "3.7"

services:
  apps:
    build: .
    image: "apps-inoeg:main"
    environment:
      - KIEBITZ_STORAGE_ENDPOINT=http://localhost:11111/jsonrpc
      - KIEBITZ_APPOINTMENTS_ENDPOINT=http://localhost:22222/jsonrpc
    depends_on:
      - backend
    ports:
      - 3000:3000

  backend:
    image: "ghcr.io/kiebitz-oss/services-inoeg:latest"
    depends_on:
      - redis
    environment:
      - KIEBITZ_SETTINGS=/settings
    volumes:
      - "./tests/fixtures/keys:/settings"
    ports:
      - 11111:11111
      - 22222:22222
    command: "./kiebitz --level debug run all"

  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
    volumes:
      - "./node_modules/.cache/redis:/data"
    command: "redis-server --loglevel verbose"
