version: "3.7"

services:
  apps:
    # image: "ghcr.io/impfen/apps-inoeg:main"
    build:
      context: .
      args:
        - VITE_IMPFEN_APPOINTMENTS_ENDPOINT=${VITE_IMPFEN_APPOINTMENTS_ENDPOINT:-http://localhost:22222/jsonrpc}
        - VITE_IMPFEN_STORAGE_ENDPOINT=${VITE_IMPFEN_STORAGE_ENDPOINT:-http://localhost:11111/jsonrpc}
    image: "apps-inoeg:main"
    depends_on:
      - backend
    ports:
      - 3000:3000

  backend:
    image: "ghcr.io/impfen/services-inoeg:main"
    depends_on:
      - redis
    environment:
      - KIEBITZ_SETTINGS=/settings
    volumes:
      - "./tests/fixtures/keys:/settings"
    ports:
      - 11111:11111
      - 22222:22222
    command: "./kiebitz --level trace run all"

  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
    volumes:
      - "./.cache/redis:/data"
    command: "redis-server --loglevel verbose"
